NAME = replace

SRCS = main.cpp Replacement.cpp

d: $(NAME)

$(NAME): $(SRCS)
	g++ -Wd -Wextra -Werror -std=c++98 $(SRCS) -o $(NAME)

clean:
	rm -fr $(NAME)

fclean: clean

re: fclean d

.PHONY: d clean fclean re